# ───────────────────────────────────────────────────
# ペインの開始番号を 0 から 1 に変更する
set-option -g base-index 1

# マウスでウィンドウ・ペインの切り替えやリサイズを可能にする (tmux 2.1以降)
set-option -g mouse on
# tmux 2.0以前を使う場合は以下を有効に
# set-option -g mode-mouse on
# set-option -g mouse-select-window on
# set-option -g mouse-select-pane on
# set-option -g mouse-resize-pane on


# ステータスバーの背景色を変更する
# set-option -g status-bg "colour255"

# コピーモードのキー操作をviライクにする
set-window-option -g mode-keys vi

# コピーした際にWindowsのクリップボードにも転送する (要 xsel)
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -bi"
# ───────────────────────────────────────────────────

# ───────────────────────────────────────────────────
# プレフィクスキーなしのキーバインド

# 縦分割（右側に新しいペイン）: Alt+Shift+d
bind -n M-D split-window -h

# 横分割（下側に新しいペイン）: Alt+d
unbind-key M-d
bind -n M-d split-window -v

# セッションから一時的に抜ける（detach）: Ctrl+Shift+d
bind -n C-a detach

# セッション終了（kill-session）: Ctrl+d
bind -n C-d kill-session

# ペインサイズの変更（左／下／上／右）: Alt+h/j/k/l
bind -n M-h resize-pane -L
bind -n M-j resize-pane -D
bind -n M-k resize-pane -U
bind -n M-l resize-pane -R

# ペイン間の移動（左／下／上／右）: Ctrl+h/j/k/l
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

unbind -n C-u
bind -n C-u copy-mode \; send-keys -X halfpage-up

unbind -n C-o
bind -n C-o copy-mode \; send-keys -X halfpage-down
